### ISSUE TITLE
Wrong hash value for files of a certain size (929271B)

### ISSUE THREAD

**Issue by styf3000** [ogay/sha2#4]
Hi @ogay,

I have found that the calculated value for the sha256 hash of a file of a certain size gives the wrong result.
I came across this by chance when calculating the hash for a file of 929271 bytes, the content of the file does
not seem to matter.

I have uploaded a file with random content of the given size.
The sha256 calculated for it is 6d5f6dc58bda07d15c37b5da73e6639ee0722971855a7aff4dc503c5cd193c9c
But if i use any other hashing tools like sha256sum from linux i get: 8c14f43ad81026351e9b60025b5420e6072ff617f5c72145b179599211514947
[testFile.txt](https://github.com/ogay/sha2/files/15405142/testFile.txt)

If you add or remove any character from the file then the hash value is correct again.
I haven't found any other file sizes that produce the same error but I assume there are more. 

I was able to pin down the error to the line:
https://github.com/ogay/sha2/blob/72f481f179bf0bf71392e860f189d076c9a150c3/sha2.c#L608

It seems to be one of the latest commits. Unfortunately I haven't been able to figure out the problem myself,
thats why I ask for your help.

Thanks :)

**Comment by ogay** [comment]
Thank you @styf3000 for reporting this. It's a regression when adding support for 64-bit type length. I pushed a fix in 9b511cc. Please confirm it fixes your issue.

**Comment by styf3000** [comment]
It works fine for me now, thank you.
Does removing that line limit the max size of the message to 512Mb again?

**Comment by ogay** [comment]
No, it does not. The max size is (2 ^ 61) - 1 bytes.
